apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: dev-ns

# nameSuffix: -dev

commonLabels:
  app: k-app-dev

configMapGenerator:
- name: demo-k-app-configmap
  literals:
  - environment=development-env

patchesStrategicMerge:
  - ingress.yaml